{
    "openapi": "3.0.0",
    "info": {
      "title": "Control Users and Addresses Documentation",
      "description": "This is an API to control users and addresses",
      "version": "1.0.0",
      "contact": {
        "email": "adller.eel.ufsc@gmail.com"
      }
    },
    "paths": {
        "/users": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create a user",
                "description": "Create a new user with name, email and password",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "user1",
                                    "email":"user1@test.com",
                                    "password": "123123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "User created!"
                    },
                    "400": {
                        "description": "Email address already used!"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            },

            "delete": {
                "tags": [
                    "User"
                ],
                "summary": "Delete a user",
                "description": "Delete a authenticated user",
                "security": [
                    { "bearerAuth": []}
                ],
                "responses": {
                    "200": {
                        "description": "User deleted!"
                    },
                    "400": {
                        "description": "User not found!"
                    },
                    "401": {
                        "description": "Unauthorized user"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            }


        },

        "/sessions": {
            "post": {
                "tags": [
                    "User Session"
                ],
                "summary": "Authenticate a user",
                "description": "Authenticate a new user with email and password",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "email":"user1@test.com",
                                    "password": "123123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User authenticated!"
                    },
                    "401": {
                        "description": "Incorrect email/password combination!"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            }
        },
    
        "/profile": {
            "put": {
                "tags": [
                    "User Profile"
                ],
                "summary": "Update user profile",
                "description": "update data from user",
                "security": [
                    { "bearerAuth": []}
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "old_password": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "password_confirmation": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name":"user1",
                                    "email":"user1@test.com",
                                    "old_password": "123123",
                                    "password": "123123",
                                    "password_confirmation": "123123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "See data user"
                    },
                    "400": {
                        "description": "User not found!"
                    },
                    "401": {
                        "description": "Unauthorized user"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            },
    
            "get": {
                "tags": [
                    "User Profile"
                ],
                "summary": "Get user profile",
                "description": "Get data from user profile",
                "security": [
                    { "bearerAuth": []}
                ],
                "responses": {
                    "200": {
                        "description": "See data from user"
                    },
                    "400": {
                        "description": "User not found!"
                    },
                    "401": {
                        "description": "Unauthorized user"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            }

        },

        "/addresses": {

            "post": {
                "tags": [
                    "Address"
                ],
                "summary": "Create a address",
                "description": "Create a new address with country, state, city, district, street, and address_number",
                "security": [
                    { "bearerAuth": []}
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "country": {
                                        "type": "string"
                                    },
                                    "state": {
                                        "type": "string"
                                    },
                                    "city": {
                                        "type": "string"
                                    },
                                    "district": {
                                        "type": "string"
                                    },
                                    "street": {
                                        "type": "string"
                                    },
                                    "address_number": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "country": "Brasil",
                                    "state":"Paraná",
                                    "city": "Curitiba",
                                    "district": "Batel",
                                    "street": "Agustinho Brás",
                                    "address_number": "545"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Address created!"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            }
            

            


        },

        "/addresses/{user_id}/my-addresses?country=": {
            "get": {
                "tags":["Address"],
                "summary": "Get address using query and route params",
                "description": "get addresses from authenticated user searching one country",
                "security": [
                    { "bearerAuth": []}
                ],
                "parameters": [{
                    "in": "path",
                    "name": "user_id",
                    
                    "schema":{
                        "type": "string"
                    },
                    "required": true,
                    "description": "String Id from user is required"
                },
                {
                    "in":"query",
                    "name": "country",
                    "schema": {
                        "type": "string"
                    },
                    "description": "Search address by country!"
                }
            
                ], 
                "responses":{
                    "200": {
                        "description": "success"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            }
        },





        "/addresses/update-address/{address_id}": {
            "put": {
                "tags":["Address"],
                "summary": "Update a address using route params",
                "description": "Update a address with country, state, city, district, street, and address_number",
                "security": [
                    { "bearerAuth": []}
                ],
                "parameters": [{
                    "in": "path",
                    "name": "address_id",
                    
                    "schema":{
                        "type": "string"
                    },
                    "required": true,
                    "description": "String Id from address is required"
                }], 
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "country": {
                                        "type": "string"
                                    },
                                    "state": {
                                        "type": "string"
                                    },
                                    "city": {
                                        "type": "string"
                                    },
                                    "district": {
                                        "type": "string"
                                    },
                                    "street": {
                                        "type": "string"
                                    },
                                    "address_number": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "country": "Brasil",
                                    "state":"Paraná",
                                    "city": "Curitiba",
                                    "district": "Batel",
                                    "street": "Augustinho Brás",
                                    "address_number": "555"
                                }
                            }
                        }
                    }
                },
                "responses":{
                    "200": {
                        "description": "Update address"
                    },
                    "400": {
                        "description": "You are not allowed to update this address!"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            }
        },




        "/addresses/delete-address/{address_id}": {
            "delete": {
                "tags":["Address"],
                "summary": "Delete address using route params",
                "description": "Delete one address from authenticated user",
                "security": [
                    { "bearerAuth": []}
                ],
                "parameters": [{
                    "in": "path",
                    "name": "address_id",
                    
                    "schema":{
                        "type": "string"
                    },
                    "required": true,
                    "description": "String Id from address is required"
                }], 
                "responses":{
                    "200": {
                        "description": "Delete address"
                    },
                    "400": {
                        "description": "You are not allowed to delete this address!"
                    },
                    "500": {
                        "description": "Internal server error!"
                    }
                }
            }
        }

        





        


    
    

    },
    "components": {
        "securitySchemes": {
          "bearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
          }
        }
    }
}